OOAD2/OOAD/survey_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('surveys/', include('surveys.urls')),
]

urlpatterns += staticfiles_urlpatterns()

OOAD2/OOAD/surveys/urls.py
from django.urls import path
from . import views
from .views import deleteview
from django.contrib.auth import views as auth_views
from surveys.views import student
from django.conf.urls import include,url

#from django.contrib import admin
#from users import views as user_views

urlpatterns = [
    path('', views.home, name='home-page'),
    path('login/', auth_views.LoginView.as_view(template_name='surveys/login.html',redirect_authenticated_user=True), name='login-page'),
    path('logout/', auth_views.LogoutView.as_view(template_name='surveys/logout.html'), name='logout-page'),
    path('staff/', views.staff, name='staff-page'), 
    path('status/', views.status, name='status-page'),
    path('dashboard/', views.staff_dashboard, name='staff_dashboard-page'),
    path('stdashboard/', views.stdashboard, name='student_dashboard-page'),
    path('student/', views.student, name='student-page'),
    path('<int:pk>/delete/', deleteview.as_view(),name='form-delete'),
    #path('delete/', views.delete_new, name='form-delete'),	
    #url(r'^admin/', admin.site.urls),

]

OOAD2/OOAD/surveys/models.py
from django.db import models
from django import forms
#from django.forms import ModelForm
#from django.urls import reverse
#from django.contrib.auth.models import User
Lecturer1= [
    ('s','Sujjala Shetty'),
    ('p','priti bajpy' ),
    ('sa','Santosh'),
    ('k','k.kumar'),
    ]
Lecturer2= [
    ('s','Sujjala Shetty'),
    ('p','priti bajpy' ),
    ('sa','Santosh'),
    ('k','k.kumar'),
    ]

class Snipp(models.Model):
    FirstName = models.CharField(max_length=100)
    LastName = models.CharField(max_length=100)
    BITSID = models.CharField(max_length=100)
    Address = models.CharField(max_length=1000)
    Reason = models.CharField(max_length=1000)
    Email = models.EmailField()
    #RequestDate =  models.DateTimeField(default='date')
    #ReturnDate = models.DateField(default='date')
    RequestDate =models.CharField(max_length=100)
    ReturnDate = models.CharField(max_length=100)
    Lecture1 = models.CharField(max_length=100,choices=Lecturer1)
    Lecture2 = models.CharField(max_length=100,choices=Lecturer2)
    def __str__(self):
        return self.FirstName+" "+self.LastName
#User = models.ForeignKey(User, on_delete=models.CASCADE)
"""    
    class RequestForm(ModelForm):
    class Meta:
        model = Request
        fields = ['FirstName', 'LastName', 'BITSID','Address','Reason','sender']
"""

OOAD2/OOAD/surveys/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,Submit
from django.contrib.auth.models import User
from .models import Snipp


class SnippetForm(forms.ModelForm):
	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)

		self.helper = FormHelper
		self.helper.form_method = "POST"
		self.helper.layout = Layout(
			'FirstName',
			'LastName',
			'BITSID',
			'Reason',
			'Address',
			'Email',
			'RequestDate',
			'ReturnDate',
			'Lecture1',
			'Lecture2',
			Submit('submit','Submit',css_class="btn-success"))
	
	class Meta:
		model = Snipp
		fields = ['FirstName', 'LastName', 'BITSID','Address','Reason','Email','RequestDate','ReturnDate','Lecture1','Lecture2']
#

OOAD2/OOAD/surveys/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from surveys.models import Snipp
from django.urls import reverse_lazy
#from django.contrib.auth.models import User
from django.contrib import admin,messages
from django.contrib.auth.models import User
#from django.contrib.admin import user
# 	from surveys.models import Request
#from django import forms
from django.views.generic.edit import CreateView,UpdateView,DeleteView
#from django.views.generic import TemplateView
from surveys.forms import SnippetForm
from django.template.loader import render_to_string
from django.utils.html import strip_tags





def home(request):
	return render(request, 'surveys/home.html')	 
def status(request):
	if request.user.is_staff :
		response = redirect('staff_dashboard-page')
	else:
		response = redirect('student_dashboard-page')
	return response	
def login(request):
	if request.user.is_authenticated():
		response= redirect('student_dashboard-page')
	else:
		response= redirect('login-page')
	return response
	#return render(request, 'surveys/login.html')

def staff_dashboard(request):
	return render(request, 'surveys/dash/dashboard_home.html')

def staff(request):
	form=SnippetForm()
	posts=Snipp.objects.all()

	#print(posts)
	#obj = Snippet.objects.get(id=16)
	#context = {
	#'FirstName':obj.FirstName,
	#'LastName':obj.LastName,
	#'BITSID':obj.BITSID,
	#'Reason':obj.Reason

	#}
	args={'form':form,'posts':posts}
	return render(request, 'surveys/dash/dashboard.html',args)
@login_required
def stdashboard(request):
	return render(request, 'surveys/dash/student_dashboard.html')
@login_required
def student(request):
	

	if request.method == 'POST':
		
		form = SnippetForm(request.POST)
		if form.is_valid():

			FirstName=form.cleaned_data['FirstName']
			LastName=form.cleaned_data['LastName']
			Lecture1=form.cleaned_data['Lecture1']
			Lecture2=form.cleaned_data['Lecture2']
			BITSID=form.cleaned_data['BITSID']
			Reason=form.cleaned_data['Reason']
			Email=form.cleaned_data['Email']
			RequestDate=form.cleaned_data['RequestDate']
			ReturnDate=form.cleaned_data['ReturnDate']
			Address=form.cleaned_data['Address']
			form.save()
			print(ReturnDate+RequestDate)
			messages.success(request, 'Your Request has been forwarded successfully')
			html_message = render_to_string('status.html', {'context': "FirstName"})
			plain_message = strip_tags(html_message)
			
			if Lecture1=='s':
				send_mail('Request Form',plain_message,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],html_message=html_message,fail_silently=False)
				
			"""
			elif Lecture1=='p':
				send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
			elif Lecture1=='sa':
				send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
			elif Lecture1=='k':
				send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)

			if Lecture2=='s':
				send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
			elif Lecture2=='p':
				send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
			elif Lecture2=='sa':
				send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
			elif Lecture2=='k':
				send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
		"""

		else:
			form = SnippetForm()
	form = SnippetForm()
	return render(request, 'surveys/dash/studentoriginal.html',{'form':form})
#def delete_new(request):

	#print(posts)
	#obj = Snippet.objects.get(id=16)
	#context = {
	#'FirstName':obj.FirstName,
	#'LastName':obj.LastName,
	#'BITSID':obj.BITSID,
	#'Reason':obj.Reason

	#}

	   #+some code to check if New belongs to logged in user
    #u = post.objects.get(pk=id).delete()
    #form=SnippetForm()
    #posts=Snippet.objects.all()
    #args={'form':form,'posts':posts}

    #return render(request, 'surveys/dash/dashboard.html')


"""

def delete_new(request, new_id):
    new_to_delete = get_object_or_404(New, id=new_id)
    #+some code to check if this object belongs to the logged in user

    if request.method == 'POST':
        form = DeleteNewForm(request.POST, instance=new_to_delete)

        if form.is_valid(): # checks CSRF
            new_to_delete.delete()
            return HttpResponseRedirect("/") # wherever to go after deleting

    else:
        form = DeleteNewForm(instance=new_to_delete)

    template_vars = {'form': form}
    return render(request, 'surveys/dash/dashboard.html', template_vars)
"""

class deleteview(DeleteView):
	model = Snipp
	success_url = reverse_lazy('staff-page')
	def test_func(self):
		post = self.get_object()                     
		return False
        #return(reverse('staff-page'))

"""	
template_name='surveys/dash/dashboard.html'
	def get_object(self):
		id_=self.kwargs.get("id")
		return get_object_or_404(posts,id=id_)

	def get_success_url(self):
		return reverse('staff-page')


def deleteview(request,pk):
	template_name='surveys/dash/dashboard.html'
	posts=get_object_or_404(Snippet,pk=pk)
	if request.method=="POST":


#return render(request, 'surveys/dash/dashboard.html')

	form = RequestForm(request.POST)
	if request.method == 'POST':
		form = RequestForm(request.POST)
		FirstName = request.POST.get("FirstName")
		LastName = request.POST.get("LastName")
		BITSID = request.POST.get("BITSID")
		Address = request.POST.get("Address")
		Email = request.POST.get("Email")
		MobileNum = request.POST.get("MobileNum")
		Reason = request.POST.get("Reason")
		Lecture1 = request.POST.get("Lecture1")
		Lecture2 = request.POST.get("Lecture2")
		send_mail('Request Form',FirstName,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)

		if form.is_valid():
			form.save()
			FirstName = form.cleaned_data.get('FirstName')
			LastName = form.cleaned_data.get('LastName')
			BITSID = form.cleaned_data.get('BITSID')
			Address = form.cleaned_data.get('Address')
			Email = form.cleaned_data.get('Email')
			MobileNum = form.cleaned_data.get('MobileNum')
			Reason = form.cleaned_data.get('Reason')
			Lecture1 = form.cleaned_data.get('Lecture1')
			Lecture2 = form.cleaned_data.get('Lecture2')
			return redirect('student-page')
	return render(request, 'surveys/dash/student.html',{'form':form})



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('blog-home')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})






class student(LoginRequiredMixin,TemplateView):
	template_name = 'surveys/dash/student.html'
	def get(self,request):
		form = RequestForm()
		return render(request,self.template_name,{'form':form})
	def Request(self,request):
		form = RequestForm(request.POST)
		if form.is_valid():
			Request=form.save(commit=False)
			Request.User = request.User
			Request.save()
			FirstName = form.cleaned_data['FirstName']
			LastName = form.cleaned_data['LastName']
			BITSID = form.cleaned_data['BITSID']
			Address = form.cleaned_data['Address']
			Email = form.cleaned_data['Email']
			MobileNum = form.cleaned_data['MobileNum']
			Reason = form.cleaned_data['Reason']
			Lecture1 = form.cleaned_data['Lecture1']
			Lecture2 = form.cleaned_data['Lecture2']
			form=RequestForm()
			return redirect('student-page') 
		args={'form':form,'text':text}
		return render(request, self.template_name,args)




		#if(Lecture2>0):
		#	if(Lecture2==1):
		#			send_mail('Request Form',message,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
		

		
		
	#return render(request, 'surveys/dash/student.html',{'form':form, })


			FirstName = request.POST.get("FirstName")
			LastName = request.POST.get("LastName")
			BITSID = request.POST.get("BITSID")
			Address = request.POST.get("Address")
			Email = request.POST.get("Email")
			MobileNum = request.POST.get("MobileNum")
			Reason = request.POST.get("Reason")
			Lecture1 = request.POST.get("Lecture1")
			Lecture2 = request.POST.get("Lecture2")
			Request_obj = Request(FirstName=FirstName,LastName=LastName,BITSID=BITSID,Address=Address,Email=Email,MobileNum=MobileNum,Reason=Reason,Lecture1=Lecture1,Lecture2=Lecture2)
			Request_obj.save()
			print(FirstName,LastName,BITSID,Address,Email,MobileNum,Reason,Lecture2,Lecture1)
			message = FirstName+BITSID+Reason
						if(Lecture1 == '1'):
				print('its done')
				send_mail('Request Form',message,settings.EMAIL_HOST_USER,['sreenumalae@gmail.com'],fail_silently=False)
			elif(Lecture1== '2'):
				send_mail('Request Form',message,settings.EMAIL_HOST_USER,['anamprudhvikumarreddy@gmail.com'],fail_silently=False)

"""

OOAD2/OOAD/surveys/templates/surveys/dash/Student.html
{%load crispy_forms_tags%}

<!DOCTYPE html>


<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>trail</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <form method="POST" >
    {% crispy form form.helper %}
    }
  </form>
  
</body>

OOAD2/OOAD/surveys/templates/surveys/dash/dashboard_home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Dashboard</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css'%}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin.css'%}" rel="stylesheet">

</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="">Passport Request</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'staff-page' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Passport Requests</span></a>
      </li>
     
    </ul>

    <div id="content-wrapper"> 
    </br></br></br></br> 
    <div> 
      </br></br>
      <center><img src="{% static 'images/bits_logo.png'%}" alt="what image shows" height="auto" width="75%"></center>

    </div>
    </div>
    <!--
    <img src="{% static 'images/bits_logo.png'%}" id ="logo" class="img" alt="Logo" style  ="height: 80%; width:100%;    border-radius:0; float:right; margin-left:20p;">
     /.content-wrapper -->


  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout-page' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin.min.js' %}"></script>

  <!-- Demo scripts for this page-->
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>

OOAD2/OOAD/surveys/templates/surveys/dash/studentoriginal.html
{% load staticfiles %}
{%load crispy_forms_tags%}
<!DOCTYPE html>


<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RequestForm</title>


  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css'%}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/gijgo.min.css'%}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/sb-admin.css'%}" rel="stylesheet">

</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">Student page</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      
      
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout-page' %}" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'student_dashboard-page' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'student-page' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Passport Request</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-fw fa-table"></i>
          <span>NOC Request</span></a>
      </li>
    </ul>


    <div id="content-wrapper" >
      {% if messages %}
      <div class='row'>
        <div class="col-xs-12">
          

    {% for message in messages %}
    <p {% if message.tags == "success" %} class="alert alert-success"{% endif %}>{{ message }}</p>
    {% endfor %}


        </div>
      </div>
      {% endif %}
      <form  method="POST" class="md-form" >
        {% crispy form form.helper %}
      </form>
    </div>
  </div>
</body>
  <!-- Logout Modal-->
   <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout-page' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin.min.js' %}"></script>

  <!-- Demo scripts for this page-->
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

  
    <script src="{% static 'js/gijgo.min.js'%}" type="text/javascript"></script>
      
  <script>
     $('#id_RequestDate').datepicker({uiLibrary: 'bootstrap4', iconsLibrary: 'fontawesome' });
 </script>
 <script>
     $('#id_ReturnDate').datepicker({ uiLibrary: 'bootstrap4', iconsLibrary: 'fontawesome' });
 </script>
</body>
   <style class="cp-pen-styles">#app {
  text-align: center;
}
img {
     width: 40%;
    margin: auto;
    display: block;
    border-radius: 53%;
    float: left;
    margin-bottom: 10px;
}
body{
  margin: 0;
  padding: 0;
  font-family: sans-serif;
}
.formBox{
  margin-top: 90px;
  padding: 50px;
}
.formBox  h1{
  margin: 0;
  padding: 0;
  text-align: center;
  margin-bottom: 50px;
  text-transform: uppercase;
  font-size: 48px;
}
.inputBox{
  position: relative;
  box-sizing: border-box;
  margin-bottom: 50px;
}
.inputBox .inputText{
  position: absolute;
    font-size: 16px;
    line-height: 30px;
    transition: .5s;
    opacity: .5;
}
.inputBox .input{
  position: relative;
  width: 100%;
  height: 50px;
  background: transparent;
  border: none;
    outline: none;
    font-size: 24px;
    border-bottom: 1px solid rgba(0,0,0,.5);


}
.focus .inputText{
  transform: translateY(-30px);
  font-size: 18px;
  opacity: 1;
  color: #00bcd4;

}
textarea{
  height: 40px !important;
}
.success

.button{
  width: 70%;
    height: 50px;
    border: none;
    outline: none;
    background: #03A9F4;
    color: #fff;
}
button {
  
}</style>
      <div class="col-sm-6">  
    <div class="form-group">
  
    <script>

// Tooltips
$('.tip').each(function () {
  $(this).tooltip(
  {
    html: true,
    title: $('#' + $(this).data('tip')).html()
  });
});


</html>